"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "ar" | "en";

export const translations: Record<Language, Record<string, string>> = {
  ar: {
    "home.title": "هنا هيكون المتجر",
    "home.tagline": "اطلبي من أي مكان، توصلك في بيتك",
    "home.sub": "قريبًا: المنتجات، الأقسام، وعروض الموسم هتظهر هنا.",
    "home.welcome": "أهلاً بكِ في بيليكو",
    "home.welcomeBack": "أهلاً بكِ مجدداً،",
    "home.allProducts": "كل المعروضات",
    "home.tab.fashion": "فاشون",
    "home.tab.beauty": "بيوتي",
    "home.tab.home": "هوم وير",
    "home.tab.summer": "صيف 2026",
    "home.tab.picks": "اختيارات المؤثرين",
    "home.search": "دوّري على أي حاجة...",
    "home.search.results": "نتائج البحث",
    "home.search.popular": "عمليات البحث الشائعة",
    "home.search.noResults": "لم يتم العثور على منتجات مطابقة",
    "home.search.tryAgain": "جربي البحث بكلمات أو تصنيفات أخرى",
    "home.premiumBrands": "ماركات مميزة",
    "common.seeAll": "شوفي الكل",
    "home.fastTitle": "توصيل سريع لمصر خلال 10-17 يوم عمل",
    "home.weekTrend": "ترند الأسبوع ده",
    "home.productSoon": "قريبًا",
    "home.checkPrice": "اعرفي السعر الحالي",
    "home.recheckPrice": "تحديث السعر",
    "home.sheinDayEyebrow": "SHEIN",
    "home.sheinDayTitle": "Brands Day",
    "cat.women": "حريمي",
    "cat.men": "رجالي",
    "cat.kids": "أطفال",
    "cat.premium": "بريميوم",
    "cat.sale": "تخفيضات",
    "cat.soon": "قريبًا",
    "account.guest": "حسابك",
    "account.personalInfo": "بياناتي الشخصية",
    "account.address": "عنواني",
    "account.myOrders": "طلباتي",
    "account.tracking": "تتبع الشحنات",
    "account.help": "التواصل والمساعدة",
    "account.settings": "الإعدادات واللغة",
    "account.logout": "تسجيل الخروج",
    "orders.loading": "بنجيب طلباتك...",
    "orders.empty": "لسه معملتيش أي طلب.",
    "status.awaiting_calculation": "بانتظار تسعير الطلب",
    "status.priced": "جاهز للدفع",
    "status.payment_pending_review": "مراجعة إثبات الدفع",
    "status.payment_flagged": "إثبات الدفع يحتاج مراجعة",
    "status.payment_confirmed": "تم تأكيد الدفع",
    "status.ordered": "تم الطلب من المتجر الأصلي",
    "status.pending": "قيد المراجعة والتأكيد",
    "status.confirmed": "تم التأكيد",
    "status.preparing": "جاري التجهيز",
    "status.shipped": "في الطريق إليك",
    "status.delivered": "تم التوصيل",
    "status.cancelled": "ملغي",
    "notif.title": "مركز الإشعارات",
    "notif.sub": "تابعي أحدث مستجدات طلباتك، التخفيضات الحصرية، والعروض الجديدة أولاً بأول",
    "notif.markAllRead": "تحديد الكل كمقروء",
    "notif.clearAll": "مسح الكل",
    "notif.all": "الكل",
    "notif.orders": "الطلبات والتتبع",
    "notif.offers": "العروض والمجموعات",
    "notif.system": "النظام والحساب",
    "notif.empty": "لا توجد إشعارات جديدة حالياً",
    "notif.emptySub": "سنرسل إليكِ إشعاراً فور تحديث حالة طلباتك أو نزول تشكيلات جديدة.",
    "notif.clearedSuccess": "تم مسح جميع الإشعارات",
    "notif.markedReadSuccess": "تم تحديد الإشعارات كمقروءة",
    "reels.share": "مشاركة",
    "reels.comments": "التعليقات",
    "reels.addComment": "اكتبي تعليق...",
    "reels.shopNow": "تسوقي دلوقتي",
    "reels.empty": "لا توجد فيديوهات منشورة حالياً",
    "reels.error": "تعذر تشغيل الفيديو، تأكدي من اتصال الإنترنت",
    "location.detecting": "بنحدد موقعك...",
    "location.egypt": "مصر (EGP)",
    "location.uae": "الإمارات (AED)",
    "location.saudi": "السعودية (SAR)",
    "location.select": "اختاري دولة التوصيل والعملة",
    "calc.title": "احسبيلي السعر",
    "calc.sub": "اعرفي التكلفة النهائية بالجنيه المصري شاملة الشحن لمنتجات شي إن وترينديول",
    "tab.home": "الرئيسية",
    "tab.reels": "ريلز",
    "tab.calc": "احسبيلي",
    "tab.account": "حسابي",
    "tab.bag": "الشنطة",
    "currency.egp": "ج.م",
    "currency.aed": "د.إ",
    "currency.sar": "ر.س",
    "currency.usd": "دولار",
    "product.addToBag": "إضافة للشنطة",
    "product.selectSize": "اختاري المقاس",
    "product.selectColor": "اختاري اللون",
    "product.details": "تفاصيل المنتج",
    "product.deliveryInfo": "شحن وتوصيل سريع لباب بيتك مع إمكانية المعاينة عند الاستلام",
    "policy.about": "من نحن",
    "policy.aboutBody": "بيليكو منصة تسوق متكاملة تتيح لك طلب أي منتجات من كبرى المتاجر والبراندات العالمية (مثل شي إن، ترينديول، وغيرها) مع توفير خدمة الشحن والتخليص والتوصيل السريع إلى باب بيتك في مصر والإمارات.",
    "policy.shipping": "سياسة الشحن",
    "policy.shippingBody": "يتم شحن وتوصيل الطلبات خلال 10 إلى 17 يوم عمل من تاريخ تأكيد الطلب. نوفر تغطية شاملة لجميع المحافظات في جمهورية مصر العربية والإمارات مع إمكانية التتبع المباشر.",
    "policy.orders": "سياسة الطلبات",
    "policy.ordersBody": "يتم تأكيد الطلب بعد دفع العربون أو القيمة المقررة. يمكنك مراجعة تفاصيل طلباتك وتحديث عنوانك وحساب السعر عبر تطبيق بيليكو بكل سهولة.",
    "policy.returns": "سياسة الاسترجاع",
    "policy.returnsBody": "نضمن لك مطابقة المنتج للمواصفات المعروضة وفحص الجودة قبل الاستلام، وفي حال وجود أي عيب مصنعي يتم التواصل مع فريق الدعم فوراً لإجراء اللازم.",
    "policy.disclaimer": "إخلاء المسؤولية",
    "policy.disclaimerBody": "بيليكو وسيط وخدمة تسوق وشحن لمنتجات المتاجر العالمية ولا تتحمل المنصة المسؤولية عن تغيير المتاجر الأصلية لسياسات التوفر أو الأسعار دون إشعار مسبق.",
    "product.guarantee": "ضمان أصالة وجودة القطعة بنسبة 100%",
    "product.totalPrice": "السعر الإجمالي",
    "placement.featured": "مميز",
    "placement.new_arrival": "وصل حديثاً",
    "placement.influencer_pick": "اختيار البلوجرز",
    "placement.trending": "الأكثر طلباً",
    "cart.title": "شنطة التسوق",
    "cart.empty": "شنطة التسوق فاضية حالياً",
    "cart.emptySub": "تصفحي أحدث الموديلات وأضيفي قطعك المفضلة للطلب",
    "cart.startShopping": "ابدئي التسوق الآن",
    "cart.items": "القطع في الشنطة",
    "cart.summary": "ملخص الطلب",
    "cart.subtotal": "المجموع الفرعي",
    "cart.shipping": "الشحن والتوصيل",
    "cart.shippingFree": "حسب العنوان",
    "cart.total": "الإجمالي",
    "cart.checkout": "بيانات استلام الطلب",
    "cart.savedAddresses": "العناوين المسجلة",
    "cart.useNewAddress": "استخدام عنوان جديد",
    "cart.autoDetectLocation": "تحديد العنوان بموقعي الحالي",
    "cart.detectingLocation": "جاري تحديد موقعك بدقة...",
    "cart.locationDetected": "تم تحديد العنوان والموقع بنجاح",
    "cart.locationFailed": "تعذر تحديد الموقع، يرجى كتابة العنوان",
    "cart.saveAddressForLater": "حفظ هذا العنوان لسرعة الطلب مستقبلاً",
    "cart.changeAddress": "تغيير العنوان",
    "cart.name": "الاسم بالكامل",
    "cart.phone": "رقم الهاتف (واتساب للتأكيد)",
    "cart.gov": "المحافظة / المنطقة",
    "cart.city": "المدينة / الحي",
    "cart.address": "العنوان بالتفصيل (الشارع، رقم العمارة)",
    "cart.notes": "ملاحظات إضافية على الطلب (اختياري)",
    "cart.placeOrder": "تأكيد وإرسال الطلب",
    "cart.orderSuccess": "تم تسجيل طلبك بنجاح! سيتم التواصل معك عبر الواتساب لتأكيد الشحن.",
    "address.title": "عناويني المسجلة",
    "address.sub": "أضيفي ونسقي عناوين التوصيل لاستلام طلباتك بسهولة",
    "address.add": "إضافة عنوان جديد",
    "address.empty": "لا توجد عناوين مسجلة حالياً",
    "address.emptySub": "أضيفي عنوانك لتسريع عملية الطلب والشحن",
    "address.default": "العنوان الافتراضي",
    "address.setDefault": "تعيين كافتراضي",
    "address.delete": "حذف العنوان",
    "address.save": "حفظ العنوان",
    "tracking.title": "تتبع الشحنات",
    "tracking.sub": "تابعي حالة ومسار شحنتك لحظة بلحظة برقم الطلب أو الهاتف",
    "tracking.searchPlaceholder": "ادخلي رقم الطلب أو رقم الهاتف...",
    "tracking.trackBtn": "تتبع الآن",
    "tracking.notFound": "لم يتم العثور على شحنة مطابقة",
    "tracking.steps.1": "استلام الطلب",
    "tracking.steps.2": "تسعير ومراجعة",
    "tracking.steps.3": "تجهيز الشحنة",
    "tracking.steps.4": "الشحن والتوزيع",
    "tracking.steps.5": "تم التسليم",
    "help.title": "المساعدة وخدمة العملاء",
    "help.sub": "نحن هنا لمساعدتك في أي استفسار على مدار الساعة",
    "help.whatsapp": "محادثة مباشرة عبر واتساب",
    "help.phone": "اتصال هاتفي مباشر",
    "help.faq": "الأسئلة الشائعة",
    "help.sendMsg": "إرسال رسالة للدعم",
    "help.sent": "تم إرسال استفسارك بنجاح وسنتواصل معك قريباً",
    "admin.rates.title": "أسعار صرف العملات",
    "admin.rates.sub": "تعديل أسعار التحويل المباشرة للعملات بالمتجر",
    "admin.rates.save": "حفظ أسعار الصرف",
    "admin.rates.saved": "تم تحديث أسعار الصرف بنجاح",
    "admin.badge": "لوحة الإدارة",
    "admin.title": "لوحة الإدارة",
    "admin.subtitle": "إدارة طلبات المتجر، كتالوج المنتجات، فيديوهات الريلز، ونقاط البيع (POS)",
    "admin.backToStore": "العودة للمتجر",
    "admin.role": "مسؤول",
    "admin.restricted": "لوحة الإدارة مقيدة",
    "admin.restrictedSub": "يرجى تسجيل الدخول بحساب مسؤول معتمد للوصول إلى لوحة التحكم.",
    "admin.tab.bazaar": "بازار بيليكو",
    "admin.tab.orders": "طلبات المتجر",
    "admin.tab.products": "المنتجات",
    "admin.tab.reels": "الفيديوهات",
    "admin.bazaar.sell": "بيع بالماسح",
    "admin.bazaar.inventory": "المخزون",
    "admin.bazaar.report": "التقرير والإيرادات",
    "admin.bazaar.whoIsSelling": "من البائع على هذا الجهاز؟",
    "admin.bazaar.sellerNote": "سيتم ربط جميع عمليات البيع من هذا الجهاز باسمك في التقرير.",
    "admin.bazaar.sellerPlaceholder": "اكتب اسمك...",
    "admin.bazaar.save": "حفظ",
    "admin.bazaar.sellingAs": "تبيع حالياً باسم:",
    "admin.bazaar.change": "تغيير",
    "admin.bazaar.scanQr": "امسح كود QR للمنتج",
    "admin.bazaar.stopCamera": "إيقاف الكاميرا",
    "admin.bazaar.originalPrice": "السعر الأصلي:",
    "admin.bazaar.discountLabel": "خصم إضافي (بالجنيه، اتركه 0 لو بدون خصم)",
    "admin.bazaar.finalPrice": "السعر النهائي:",
    "admin.bazaar.confirmSale": "تأكيد البيع",
    "admin.bazaar.cancel": "إلغاء",
    "admin.bazaar.recentSales": "آخر عمليات البيع",
    "admin.bazaar.noSales": "لم يتم تسجيل أي مبيعات بعد",
    "admin.bazaar.printAllQRs": "طباعة كل الأكواد (QR)",
    "admin.bazaar.importExcel": "استيراد من Excel",
    "admin.bazaar.addManualProduct": "إضافة منتج يدوي جديد",
    "admin.bazaar.productNamePlaceholder": "اسم القطعة (مثال: فستان حرير بيج)",
    "admin.bazaar.pricePlaceholder": "سعر البيع بالجنيه (مثال: 450)",
    "admin.bazaar.addToInventory": "إضافة للمخزون",
    "admin.bazaar.itemsCount": "قطع البازار",
    "admin.bazaar.noInventory": "لا توجد منتجات مسجلة بالمخزون",
    "admin.bazaar.totalSold": "إجمالي القطع المباعة",
    "admin.bazaar.totalRevenue": "إجمالي الإيرادات",
    "admin.bazaar.sellerPerformance": "أداء البائعين",
    "admin.bazaar.allSalesRecords": "سجل المبيعات الكامل",
    "admin.orders.title": "طلبات المتجر الواردة",
    "admin.orders.noOrders": "لا توجد طلبات جديدة حالياً",
    "admin.orders.filterAll": "الكل",
    "admin.products.title": "كتالوج منتجات المتجر",
    "admin.products.addNew": "إضافة منتج جديد",
    "admin.products.noProducts": "لا توجد منتجات مضافة بعد",
    "admin.products.name": "اسم المنتج",
    "admin.products.price": "السعر الأصلي (ج.م)",
    "admin.products.discountPrice": "سعر التخفيض (اختياري)",
    "admin.products.category": "القسم",
    "admin.products.placement": "مكان العرض",
    "admin.products.uploadImage": "رفع صورة المنتج",
    "admin.products.saveProduct": "حفظ ونشر المنتج",
    "admin.products.deleteConfirmTitle": "حذف منتج من المتجر",
    "admin.products.deleteConfirmMsg": "هل أنت متأكد من حذف هذا المنتج نهائياً من المتجر؟",
    "admin.reels.title": "إدارة فيديوهات الريلز",
    "admin.reels.uploadNew": "نشر فيديو ريلز جديد",
    "admin.reels.noReels": "لا توجد فيديوهات ريلز منشورة",
    "admin.reels.creator": "اسم منشئ الفيديو / البلوجر",
    "admin.reels.caption": "الوصف / الكابشن",
    "admin.reels.tagProduct": "ربط بمنتج (اختياري)",
    "admin.reels.selectVideo": "اختيار ملف الفيديو (MP4)",
    "admin.reels.publishReel": "نشر الريلز",
    "admin.reels.deleteConfirmTitle": "حذف فيديو الريلز",
    "admin.reels.deleteConfirmMsg": "هل أنت متأكد من حذف هذا الفيديو نهائياً؟",
  },
  en: {
    "home.title": "Your store starts here",
    "home.tagline": "Shop the world, delivered to you",
    "home.sub": "Coming soon: products, categories, and seasonal deals.",
    "home.welcome": "Welcome to Beleco",
    "home.welcomeBack": "Welcome back,",
    "home.allProducts": "All Products",
    "home.tab.fashion": "Fashion",
    "home.tab.beauty": "Beauty",
    "home.tab.home": "Homeware",
    "home.tab.summer": "Summer 2026",
    "home.tab.picks": "Influencer Picks",
    "home.search": "Search for anything...",
    "home.search.results": "Search Results",
    "home.search.popular": "Popular Searches",
    "home.search.noResults": "No matching products found",
    "home.search.tryAgain": "Try searching with different keywords or categories",
    "home.premiumBrands": "Premium Brands",
    "common.seeAll": "See all",
    "home.fastTitle": "Fast delivery to Egypt in 10–17 business days",
    "home.weekTrend": "Trending this week",
    "home.productSoon": "Coming soon",
    "home.checkPrice": "Check price",
    "home.recheckPrice": "Update price",
    "home.sheinDayEyebrow": "SHEIN",
    "home.sheinDayTitle": "Brands Day",
    "cat.women": "Women",
    "cat.men": "Men",
    "cat.kids": "Kids",
    "cat.premium": "Premium",
    "cat.sale": "Sale",
    "cat.soon": "Soon",
    "account.guest": "Your account",
    "account.personalInfo": "Personal Info",
    "account.address": "My Address",
    "account.myOrders": "My Orders",
    "account.tracking": "Track Shipments",
    "account.help": "Help & Contact",
    "account.settings": "Settings & Language",
    "account.logout": "Log Out",
    "status.awaiting_calculation": "Awaiting Price Calculation",
    "status.priced": "Ready to Pay",
    "status.payment_pending_review": "Payment Under Review",
    "status.payment_flagged": "Payment Flagged",
    "status.payment_confirmed": "Payment Confirmed",
    "status.ordered": "Ordered from Store",
    "status.pending": "Pending Review",
    "status.confirmed": "Confirmed",
    "status.preparing": "Preparing",
    "status.shipped": "On the way",
    "status.delivered": "Delivered",
    "status.cancelled": "Cancelled",
    "notif.title": "Notifications Center",
    "notif.sub": "Stay updated with live order tracking, exclusive drops, and promotions",
    "notif.markAllRead": "Mark all as read",
    "notif.clearAll": "Clear all",
    "notif.all": "All",
    "notif.orders": "Orders & Shipping",
    "notif.offers": "Offers & Drops",
    "notif.system": "System & Account",
    "notif.empty": "No new notifications",
    "notif.emptySub": "We'll notify you as soon as your orders update or new collections drop.",
    "notif.clearedSuccess": "All notifications cleared",
    "notif.markedReadSuccess": "All marked as read",
    "reels.share": "Share",
    "reels.comments": "Comments",
    "reels.addComment": "Write a comment...",
    "reels.shopNow": "Shop Now",
    "reels.empty": "No videos available yet",
    "reels.error": "Unable to load video. Check your connection.",
    "location.detecting": "Detecting location...",
    "location.egypt": "Egypt (EGP)",
    "location.uae": "UAE (AED)",
    "location.saudi": "Saudi (SAR)",
    "location.select": "Select Delivery Country & Currency",
    "calc.title": "Price Calculator",
    "calc.sub": "Instant final cost breakdown in Egyptian Pounds for Shein & Trendyol items",
    "tab.home": "Home",
    "tab.reels": "Reels",
    "tab.calc": "Calculate",
    "tab.account": "Account",
    "tab.bag": "Bag",
    "currency.egp": "EGP",
    "currency.aed": "AED",
    "currency.sar": "SAR",
    "currency.usd": "USD",
    "product.addToBag": "Add to Bag",
    "product.selectSize": "Select Size",
    "product.selectColor": "Select Color",
    "product.details": "Product Details",
    "product.deliveryInfo": "Fast, direct delivery with doorstep inspection upon receipt.",
    "policy.about": "About Us",
    "policy.aboutBody": "Beleco is an e-commerce platform that allows you to shop from global fashion and homeware brands (Shein, Trendyol, and more) with seamless direct delivery to Egypt and the UAE.",
    "policy.shipping": "Shipping Policy",
    "policy.shippingBody": "Orders are processed and delivered within 10 to 17 business days from confirmation, with live tracking available at every milestone.",
    "policy.orders": "Order Policy",
    "policy.ordersBody": "Orders are confirmed upon initial deposit or payment. You can track status, update delivery addresses, and view order breakdown anytime.",
    "policy.returns": "Return Policy",
    "policy.returnsBody": "We guarantee items match specifications and inspect packages before delivery. In case of manufacturing defects, reach out to customer care immediately.",
    "policy.disclaimer": "Disclaimer",
    "policy.disclaimerBody": "Beleco serves as an international shopping concierge and forwarding service. Original supplier stock and pricing are subject to merchant terms.",
    "product.guarantee": "100% Guaranteed Authenticity & Quality",
    "product.totalPrice": "Total Price",
    "placement.featured": "Featured",
    "placement.new_arrival": "New Arrival",
    "placement.influencer_pick": "Blogger Pick",
    "placement.trending": "Trending",
    "cart.title": "Shopping Bag",
    "cart.empty": "Your bag is currently empty",
    "cart.emptySub": "Explore our curated collections and add your favorite pieces",
    "cart.startShopping": "Start Shopping Now",
    "cart.items": "Items in Bag",
    "cart.summary": "Order Summary",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping & Delivery",
    "cart.shippingFree": "Calculated at delivery",
    "cart.total": "Total",
    "cart.checkout": "Delivery Details",
    "cart.savedAddresses": "Saved Addresses",
    "cart.useNewAddress": "Use a new address",
    "cart.autoDetectLocation": "Auto-fill with Current Location",
    "cart.detectingLocation": "Detecting your location...",
    "cart.locationDetected": "Location & address detected successfully",
    "cart.locationFailed": "Could not detect location. Please enter manually",
    "cart.saveAddressForLater": "Save this address for faster future checkout",
    "cart.changeAddress": "Change Address",
    "cart.name": "Full Name",
    "cart.phone": "Phone Number (WhatsApp for confirmation)",
    "cart.gov": "Governorate / Region",
    "cart.city": "City / District",
    "cart.address": "Detailed Address (Street, Building)",
    "cart.notes": "Order Notes (Optional)",
    "cart.placeOrder": "Confirm & Place Order",
    "cart.orderSuccess": "Your order has been placed successfully! We will contact you via WhatsApp.",
    "address.title": "My Saved Addresses",
    "address.sub": "Manage your delivery addresses for seamless checkout",
    "address.add": "Add New Address",
    "address.empty": "No saved addresses yet",
    "address.emptySub": "Add your address to speed up order delivery",
    "address.default": "Default Address",
    "address.setDefault": "Set as Default",
    "address.delete": "Delete Address",
    "address.save": "Save Address",
    "tracking.title": "Track Shipments",
    "tracking.sub": "Track real-time shipment status by Order ID or phone",
    "tracking.searchPlaceholder": "Enter Order ID or phone number...",
    "tracking.trackBtn": "Track Now",
    "tracking.notFound": "No matching shipment found",
    "tracking.steps.1": "Order Placed",
    "tracking.steps.2": "Price Calculation",
    "tracking.steps.3": "Packaging",
    "tracking.steps.4": "Out for Delivery",
    "tracking.steps.5": "Delivered",
    "help.title": "Help & Customer Support",
    "help.sub": "We are here to assist you 24/7",
    "help.whatsapp": "Live WhatsApp Chat",
    "help.phone": "Direct Phone Call",
    "help.faq": "Frequently Asked Questions",
    "help.sendMsg": "Send Support Message",
    "help.sent": "Your message has been sent successfully. We will contact you shortly.",
    "admin.rates.title": "Currency Exchange Rates",
    "admin.rates.sub": "Adjust live currency conversion rates for the storefront",
    "admin.rates.save": "Save Exchange Rates",
    "admin.rates.saved": "Exchange rates updated successfully",
    "admin.badge": "Admin",
    "admin.title": "Admin Dashboard",
    "admin.subtitle": "Manage store orders, catalog products, reels, and Bazaar POS",
    "admin.backToStore": "Back to Store",
    "admin.role": "Admin",
    "admin.restricted": "Admin Dashboard Restricted",
    "admin.restrictedSub": "Please log in with an authorized admin account to access the dashboard.",
    "admin.tab.bazaar": "Bazaar",
    "admin.tab.orders": "Orders",
    "admin.tab.products": "Products",
    "admin.tab.reels": "Reels",
    "admin.bazaar.sell": "Scan & Sell",
    "admin.bazaar.inventory": "Inventory",
    "admin.bazaar.report": "Reports & Revenue",
    "admin.bazaar.whoIsSelling": "Who is selling on this device?",
    "admin.bazaar.sellerNote": "All sales from this device will be linked to your name in reports.",
    "admin.bazaar.sellerPlaceholder": "Enter your name...",
    "admin.bazaar.save": "Save",
    "admin.bazaar.sellingAs": "Currently selling as:",
    "admin.bazaar.change": "Change",
    "admin.bazaar.scanQr": "Scan Product QR Code",
    "admin.bazaar.stopCamera": "Stop Camera",
    "admin.bazaar.originalPrice": "Original Price:",
    "admin.bazaar.discountLabel": "Extra Discount (EGP, 0 for none)",
    "admin.bazaar.finalPrice": "Final Price:",
    "admin.bazaar.confirmSale": "Confirm Sale",
    "admin.bazaar.cancel": "Cancel",
    "admin.bazaar.recentSales": "Recent Sales",
    "admin.bazaar.noSales": "No sales recorded yet",
    "admin.bazaar.printAllQRs": "Print All QR Codes",
    "admin.bazaar.importExcel": "Import from Excel",
    "admin.bazaar.addManualProduct": "Add Manual Product",
    "admin.bazaar.productNamePlaceholder": "Item name (e.g. Silk Beige Dress)",
    "admin.bazaar.pricePlaceholder": "Selling price in EGP (e.g. 450)",
    "admin.bazaar.addToInventory": "Add to Inventory",
    "admin.bazaar.itemsCount": "Bazaar Items",
    "admin.bazaar.noInventory": "No items in inventory",
    "admin.bazaar.totalSold": "Total Items Sold",
    "admin.bazaar.totalRevenue": "Total Revenue",
    "admin.bazaar.sellerPerformance": "Seller Performance",
    "admin.bazaar.allSalesRecords": "All Sales Records",
    "admin.orders.title": "Incoming Store Orders",
    "admin.orders.noOrders": "No new orders currently",
    "admin.orders.filterAll": "All",
    "admin.products.title": "Storefront Products Catalog",
    "admin.products.addNew": "Add New Product",
    "admin.products.noProducts": "No products added yet",
    "admin.products.name": "Product Name",
    "admin.products.price": "Original Price (EGP)",
    "admin.products.discountPrice": "Discount Price (Optional)",
    "admin.products.category": "Category",
    "admin.products.placement": "Placement",
    "admin.products.uploadImage": "Upload Product Image",
    "admin.products.saveProduct": "Save & Publish Product",
    "admin.products.deleteConfirmTitle": "Delete Storefront Product",
    "admin.products.deleteConfirmMsg": "Are you sure you want to permanently delete this product from the storefront?",
    "admin.reels.title": "Manage Video Reels",
    "admin.reels.uploadNew": "Upload New Reel",
    "admin.reels.noReels": "No reels published yet",
    "admin.reels.creator": "Creator / Blogger Name",
    "admin.reels.caption": "Caption",
    "admin.reels.tagProduct": "Tag Product (Optional)",
    "admin.reels.selectVideo": "Select Video File (MP4)",
    "admin.reels.publishReel": "Publish Reel",
    "admin.reels.deleteConfirmTitle": "Delete Reel Video",
    "admin.reels.deleteConfirmMsg": "Are you sure you want to permanently delete this video?",
  },
};

export type Direction = "rtl" | "ltr";

interface LanguageContextValue {
  lang: Language;
  dir: Direction;
  isLangReady: boolean;
  t: (key: string) => string;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>("ar");
  const [isLangReady, setIsLangReady] = useState(false);

  const dir: Direction = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    try {
      const saved = localStorage.getItem("beleco_lang") as Language;
      if (saved === "en" || saved === "ar") {
        setLang(saved);
      }
    } catch {}
    setIsLangReady(true);
  }, []);

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
      document.documentElement.dir = dir;
    }
  }, [lang, dir]);

  const setLanguage = (newLang: Language) => {
    setLang(newLang);
    try {
      localStorage.setItem("beleco_lang", newLang);
    } catch {}
  };

  const toggleLanguage = () => {
    setLanguage(lang === "ar" ? "en" : "ar");
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations["ar"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, dir, isLangReady, t, setLanguage, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
